-- Outgoing por CDU — Processo Drivers — BR_ME_Sellers_Longtail — Fev a Mai 2026
SELECT
  CDU,
  SUM(CANT_OUTGOING) AS outgoing
FROM `meli-bi-data.WHOWNER.DM_CX_OUTGOING_GESTION_DETAIL`
WHERE SIT_SITE_ID = 'MLB'
  AND CI_EVENT_NAME IN ('OUTGOING_CONTACT','OUTGOING_FIRST_CONTACT')
  AND PRO_PROCESS_NAME = 'Drivers'
  AND USER_TEAM_NAME IN ('BR_ME_Sellers_Longtail','BR_ME_Pre-Despacho_Offline')
  AND OUTGOING_DATE BETWEEN '2026-02-01' AND CURRENT_DATE() - 1
  AND CDU IS NOT NULL AND TRIM(CDU) != ''
GROUP BY CDU
ORDER BY outgoing DESC
