-- NPS Lineal por CDU — Drivers — BR_ME_Sellers_Longtail — Fev a Mai 2026
SELECT
  NP.CDU,
  COUNT(*)                                                                AS PESQ,
  ROUND((SUM(NP.PROMOTER)-SUM(NP.DETRACTOR))/NULLIF(COUNT(*),0)*100, 2) AS NPS_LINEAL,
  ROUND(SUM(NP.SURVEY_TARGET_VALUE)/NULLIF(COUNT(*),0)*100, 2)           AS TARGET
FROM `meli-bi-data.WHOWNER.DM_CX_NPS_Y20_DETAIL` NP
WHERE
  NP.RES_END_DATE >= '2026-02-01'
  AND NP.RES_END_DATE <= DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
  AND NP.ANTIGUEDAD_REP IN ('EXPERT','NEWBIE')
  AND NP.FLAG_NOT_EXCLUDED_SURVEY IS TRUE
  AND NP.FLAG_ACTIVE_TEAM IS TRUE
  AND NP.USER_TEAM_NAME IN ('BR_ME_Sellers_Longtail','BR_ME_Pre-Despacho_Offline')
  AND NP.PRO_PROCESS_NAME = 'Drivers'
  AND NP.CDU IS NOT NULL
  AND TRIM(NP.CDU) != ''
GROUP BY NP.CDU
HAVING PESQ >= 10
ORDER BY PESQ DESC
