SELECT
  NP.PRO_PROCESS_NAME AS PROCESSO,
  NP.CDU,
  NP.PRO_SOLUTION_NAME AS SOLUCAO,
  COUNT(*) AS PESQ,
  ROUND((SUM(NP.PROMOTER)-SUM(NP.DETRACTOR))/NULLIF(COUNT(*),0)*100, 2) AS NPS
FROM `meli-bi-data.WHOWNER.DM_CX_NPS_Y20_DETAIL` NP
WHERE
  NP.RES_END_DATE >= DATE_TRUNC(DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY), MONTH)
  AND NP.RES_END_DATE <= DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
  AND NP.ANTIGUEDAD_REP IN ('EXPERT','NEWBIE')
  AND NP.FLAG_NOT_EXCLUDED_SURVEY IS TRUE
  AND NP.FLAG_ACTIVE_TEAM IS TRUE
  AND NP.USER_TEAM_NAME IN ('BR_ME_Sellers_Longtail','BR_ME_Pre-Despacho_Offline')
  AND NP.PRO_PROCESS_NAME IN (
    'Viaje del paquete - Comprador',
    'Despacho Ventas y Publicaciones',
    'Drivers',
    'Reversa',
    'Places Kangu'
  )
  AND NP.CDU IS NOT NULL
  AND NP.PRO_SOLUTION_NAME IS NOT NULL
  AND TRIM(NP.CDU) != ''
GROUP BY PROCESSO, NP.CDU, NP.PRO_SOLUTION_NAME
HAVING PESQ >= 3
ORDER BY PROCESSO, NP.CDU, PESQ DESC
